In [82]:
from collections import Counter

import scanpy as sc
import pandas as pd
import numpy as np

In [83]:
n = 1000
mapping = {
    'Tumor': 5000,
    'ccRCC cancer cell': 5000,
}

In [84]:
cell_type_col = 'cell_type'

In [15]:
input_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/ccrcc_rna.h5ad'
output_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/ccrcc_downsampled.h5ad'

In [23]:
input_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/crc_rna.h5ad'
output_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/crc_downsampled.h5ad'

In [85]:
input_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/gbm_rna.h5ad'
output_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/gbm_downsampled.h5ad'

In [55]:
input_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/mm_rna.h5ad'
output_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/mm_downsampled.h5ad'

In [68]:
input_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/pdac_rna.h5ad'
output_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/pdac_downsampled.h5ad'

In [100]:
input_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/brca_rna.h5ad'
output_fp = '/diskmnt/Projects/Users/estorrs/sandbox/austin_xenium/brca_downsampled.h5ad'

In [101]:
a_rna = sc.read_h5ad(input_fp)
a_rna

AnnData object with n_obs × n_vars = 18685 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'doublet_score', 'predicted_doublet', 'percent.mito', 'nCount_SCT', 'nFeature_SCT', 'SCT_snn_res.0.5', 'seurat_clusters', 'Sample_ID', 'barcode', 'MonacoImmuneData', 'NovershternHematopoieticData', 'DatabaseImmuneCellExpressionData', 'sccatch_anno', 'customclassif', 'cell_type'
    var: 'features'

In [102]:
a_rna.obs

orig.ident  \
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AACA...     HT206B1-S1H4A2Y1_1N1Z1_1B1   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_ACGG...     HT206B1-S1H4A2Y1_1N1Z1_1B1   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGAC...     HT206B1-S1H4A2Y1_1N1Z1_1B1   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCG...     HT206B1-S1H4A2Y1_1N1Z1_1B1   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCT...     HT206B1-S1H4A2Y1_1N1Z1_1B1   
...                                                                           ...   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1   

                                                   nCount_RNA nFeature_RNA  \
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AACA...       5510         2259   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_ACGG...       1036          774   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGAC...      13777         3913   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCG...      10664         3370   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCT...       4651         2231   
...                                                       ...          ...   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...       1247          893   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...       1302          934   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...       1157          805   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...       1391          921   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...       1673          996   

                                                          doublet_score  \
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AACA...    0.274390243902439   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_ACGG...    0.274390243902439   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGAC...    0.335701598579041   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCG...    0.274390243902439   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCT...               0.2928   
...                                                                 ...   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...  0.00115207373271889   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...    0.219602977667494   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...   0.0278592375366569   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...    0.304484657749803   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...    0.116883116883117   

                                                   predicted_doublet  \
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AACA...              True   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_ACGG...              True   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGAC...              True   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCG...              True   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCT...              True   
...                                                              ...   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...             False   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...             False   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...             False   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...             False   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_T...             False   

                                                           percent.mito  \
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AACA...   0.0883847549909256   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_ACGG...   0.0627413127413127   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGAC...   0.0222835160049358   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1B1_AGCG

In [103]:
counts = Counter(a_rna.obs[cell_type_col]).most_common()
counts

[('Tumor', 8952),
 ('T_cell', 5012),
 ('Mono_Macro', 2642),
 ('Fibroblast', 783),
 ('B_cell', 395),
 ('Plasma', 266),
 ('Luminal_progenitor', 166),
 ('Endothelial_cells', 147),
 ('Basal_myoepithelial', 145),
 ('Adipocyte_CAF_mixed', 85),
 ('NK', 51),
 ('Mast?', 41)]

In [104]:
cell_type_to_ids = {}
for cell_type in sorted(set(a_rna.obs[cell_type_col])):
    f = a_rna[a_rna.obs[cell_type_col]==cell_type]
    pool = f.obs.index.to_list()
    size = min(mapping.get(cell_type, n), f.shape[0])
    ids = np.random.choice(pool, replace=False, size=size)
    cell_type_to_ids[cell_type] = ids
    
ids = []
for ls in cell_type_to_ids.values():
    ids += ls.tolist()
filtered_rna = a_rna[ids]

In [105]:
# filtered_rna = a_rna

In [106]:
counts = Counter(filtered_rna.obs[cell_type_col]).most_common()
counts

[('Tumor', 5000),
 ('Mono_Macro', 1000),
 ('T_cell', 1000),
 ('Fibroblast', 783),
 ('B_cell', 395),
 ('Plasma', 266),
 ('Luminal_progenitor', 166),
 ('Endothelial_cells', 147),
 ('Basal_myoepithelial', 145),
 ('Adipocyte_CAF_mixed', 85),
 ('NK', 51),
 ('Mast?', 41)]

In [107]:
np.unique(filtered_rna.raw.X[0].toarray())

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10., 11., 12., 16.,
       21., 39.])

In [108]:
filtered_rna.raw.var.columns = ['index']
# filtered_rna.raw.var.index = filtered_rna.raw.var['index'].to_list()
filtered_rna.layers['counts'] = filtered_rna.raw.X

keep = ['cell_type', 'orig.ident']
filtered_rna.obs = filtered_rna.obs[keep]

filtered_rna.obs

cell_type  \
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1Bn1_1_A...  Adipocyte_CAF_mixed   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_AAA...  Adipocyte_CAF_mixed   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_GTG...  Adipocyte_CAF_mixed   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_TGA...  Adipocyte_CAF_mixed   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_CAT...  Adipocyte_CAF_mixed   
...                                                                 ...   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_C...                Tumor   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_ATC...                Tumor   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_G...                Tumor   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_CTT...                Tumor   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_C...                Tumor   

                                                                       orig.ident  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1Bn1_1_A...  HT206B1-S1H4A2Y1_1N1Z1_1Bn1_1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_AAA...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_GTG...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_TGA...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_CAT...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
...                                                                           ...  
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_C...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_ATC...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_G...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_CTT...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_C...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1  

[9079 rows x 2 columns]

In [109]:
filtered_rna.write_h5ad(output_fp)

In [110]:
a = sc.read_h5ad(output_fp)
a

AnnData object with n_obs × n_vars = 9079 × 36601
    obs: 'cell_type', 'orig.ident'
    var: 'features'
    layers: 'counts'

In [111]:
a.obs

cell_type  \
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1Bn1_1_A...  Adipocyte_CAF_mixed   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_AAA...  Adipocyte_CAF_mixed   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_GTG...  Adipocyte_CAF_mixed   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_TGA...  Adipocyte_CAF_mixed   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_CAT...  Adipocyte_CAF_mixed   
...                                                                 ...   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_C...                Tumor   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_ATC...                Tumor   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_G...                Tumor   
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_CTT...                Tumor   
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_C...                Tumor   

                                                                       orig.ident  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y1_1N1Z1_1Bn1_1_A...  HT206B1-S1H4A2Y1_1N1Z1_1Bn1_1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_AAA...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_GTG...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_TGA...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_CAT...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
...                                                                           ...  
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_C...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_ATC...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_G...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1  
HTAN_BRCA_snRNA_HT206B1-S1H4A2Y2_1N3Z1_1Bn1_CTT...    HT206B1-S1H4A2Y2_1N3Z1_1Bn1  
HTAN_BRCA_snRNA_HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1_C...  HT217B1-S1H1A3Y1_1N1Z1_1Bn1_1  

[9079 rows x 2 columns]

In [112]:
np.unique(filtered_rna.layers['counts'][0].toarray())

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10., 11., 12., 16.,
       21., 39.])

In [113]:
np.unique(filtered_rna.X[0].toarray())

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10., 11., 12., 16.,
       21., 39.])